#!/bin/sh
# Points claude code at DLPNet LLM Router

export ANTHROPIC_BASE_URL=https://api.dlp.network/v1/llm/default_agentic
export CLAUDE_CODE_OAUTH_TOKEN="$(cat ~/.claude/dlp-spac)"

exec claude "$@"
