#!/bin/sh
# Points claude code at DLPNet LLM Router

export ANTHROPIC_BASE_URL=http://127.0.0.1:8080/v1/llm/default_agentic
export CLAUDE_CODE_OAUTH_TOKEN="$(cat ~/.claude/dlp-api-debug-auth-key)"

exec claude "$@"
