#!/bin/bash

if [ "$(whoami)" != "randombk" ]; then
    echo "Script must be run as randombk"
    exit 1
fi

if [ ! "${PWD##/home/randombk/dev/opensource}" != "${PWD}" ]
then
    read -p "Not in open source directory! Are you sure? " -n 1 -r
    echo    # (optional) move to a new line
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        exit 1
    fi
fi

git config user.name "David Li"
git config user.email "jiawei.davidli@gmail.com"

